# Generated by Django 3.2.25 on 2025-10-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        # Constraint removed and moved to a later migration after cleaning duplicates
    ]
