# Generated by Django 3.2.25 on 2025-10-01 12:25

from django.db import migrations, models
from django.db.models import Count


def remove_duplicate_bookings(apps, schema_editor):
    """
    Find and remove duplicate bookings before applying the unique constraint.
    Keep only the first booking from each group of duplicates.
    """
    Booking = apps.get_model('members', 'Booking')
    
    # Find duplicates (same user, listing, check_in, check_out)
    duplicates = Booking.objects.values('user', 'listing', 'check_in', 'check_out').annotate(
        count=Count('id')
    ).filter(count__gt=1)
    
    # For each group of duplicates, keep the first one and delete the rest
    for dup in duplicates:
        bookings = Booking.objects.filter(
            user=dup['user'],
            listing=dup['listing'],
            check_in=dup['check_in'],
            check_out=dup['check_out']
        ).order_by('id')
        
        # Keep the first one, delete the rest
        first_booking = bookings.first()
        bookings.exclude(id=first_booking.id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_booking_unique_booking_per_user_listing_dates'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_bookings),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('user', 'listing', 'check_in', 'check_out'), name='unique_booking_per_user_listing_dates'),
        ),
    ]
